CREATE TABLE `TEACHER` (
	`id` SERIAL,
	`USER_ID` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci,
	`PASSWORD` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
	`NAME` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB;