CREATE TABLE `SUBJECT` (
	`id` SERIAL ,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`CD` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`NAME` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
	PRIMARY KEY (`SCHOOL_CD`,`CD`)
) ENGINE=InnoDB;