CREATE TABLE `CLASS_NUM` (
    `id` SERIAL ,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci,
	`CLASS_NUM` VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_general_ci,
	PRIMARY KEY (`SCHOOL_CD`,`CLASS_NUM`)
) ENGINE=InnoDB;