CREATE TABLE `TEST` (
	`id` SERIAL ,
	`STUDENT_NO` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci,
	`SUBJECT_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
	`SCHOOL_CD` CHAR CHARACTER SET utf8 COLLATE utf8_general_ci,
	`NO` INT(10),
	`POINT` INT(10) NOT NULL,
	`CLASS_NUM` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
	PRIMARY KEY (`STUDENT_NO`,`SUBJECT_CD`,`SCHOOL_CD`,`NO`)
) ENGINE=InnoDB;